### ISSUE TITLE
SSD, 2016-2020, Aggregation

### ISSUE THREAD

**Issue by QLLZ** [HopkinsIDD/cholera-mapping-pipeline#152]
List of countries with error type "Error: Variable 'y' has NA values.":
1. SSD 2016-01-01:2020-12-31
Model executable is up to date!
Error: Variable 'y' has NA values.

**Comment by QLLZ** [comment]
This error is produced when aggregation process creates NA values

**Comment by NedaJalali-codes** [comment]
I checked the data for SSD.
The y null values are for the observation ids = 2006 and 2212, in the observation_data.I checked different data sources to see where these records are generated.
They are are generated after running  
```
observation_data_censored <- taxdat::do_censoring(temporally_linked_observations,
    unique_column_names = taxdat::get_unique_columns_by_group(temporally_linked_observations,
      grouping_columns = c("observation_id"), skip_columns = c(
        "observation_id",
        "shape", cases_column, paste0(cases_column, "_R"), paste0(
          cases_column,
          "_L"
        ), "tfrac"
      )
    ), colnames = cases_column, threshold = config[["processing"]][["censor_incomplete_observations"]][["threshold"]]
  )
```
temporally_linked_observations does not have observation ids 2006 and 2212. But after the code above, the observation_data_censored has these two records with NULL values
for suspected_cases, suspected_cases_R, suspected_cases_L.As a result, they will be added to the observation_data after  
```
observation_data <- sf::st_as_sf(taxdat::project_to_groups(
    observation_data_censored,
    "observation_id", observation_data
  ))
```

**Comment by QLLZ** [comment]
In test case, tried subsetting a group of observation_id in temporally_linked_observations, but  observation_data  seems just to remove those observations completely instead of creating a NA in sCh

**Comment by NedaJalali-codes** [comment]
solved. details in PR #169
