### ISSUE TITLE
Issues in Figures 6 and 7

### ISSUE THREAD

**Issue by NedaJalali-codes** [HopkinsIDD/cholera-mapping-pipeline#154]
Data: BEN 2016-01-01:2018-12-31
GAM Input, Observations input for the GAM model plots (Fig 6 and 7): When I run the model for BEN in 2016-01-01:2018-12-31
There is no cases in 2018, but there are 761 cases in 2016 and 11 cases in 2017.
In figure 6, the plots are shown for 17 and 18 which I assume they are related to 2017 and 2018. 
After tracing the issue, I found "stan_input$initial_values_df$t" is wrong because it equals to 17 for records in 2016 and it is equal to 18 for records in 2017. 
I am not sure t only for plotting process or you use it when running stan. If you use it, then it could be a bug and have effects on stan results. 

Data: BEN 2016-01-01:2020-12-31
For this time interval, the plots are shown for 2017, 2018, 2020, 2021 which again are wrong.

**Comment by jkamins7** [comment]
t is not used in the stan model directly. In general, t is year - 1999 (since we start time indexing at 2000). I think that probably this is just a plotting issue and that t + 2000 was used instead of t + 1999

**Comment by NedaJalali-codes** [comment]
It is solved. The related PR is #181
