### ISSUE TITLE
GAM model formula should include intercept

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/cholera-mapping-pipeline#257]
GAM model formula should include intercept
https://github.com/HopkinsIDD/cholera-mapping-pipeline/blob/3d3fd93707f72fec8294e10c12769a569a619f3f/Analysis/R/prepare_initial_values.R#L146

Stan and GAM models both should have an intercept.

**Comment by javierps** [comment]
solved on dev_stan_cleanup in commit: https://github.com/HopkinsIDD/cholera-mapping-pipeline/pull/248/commits/6542c6e674849f49b9fea2710e7c6643f37f7c2a
