### ISSUE TITLE
rename overdispersion parameter away from lambda

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/cholera-mapping-pipeline#260]
lambda is used to represent incidence rate, so it's confusing to also use it as a parameter.

Config arg, and passing of stan_params should be updated to something different.

**Comment by javierps** [comment]
Solved in on dev_stan_cleanup in commit: https://github.com/HopkinsIDD/cholera-mapping-pipeline/pull/248/commits/6542c6e674849f49b9fea2710e7c6643f37f7c2a
