### ISSUE TITLE
connect_islands missing "it" argument

### ISSUE THREAD

**Issue by KaiyueZou** [HopkinsIDD/cholera-mapping-pipeline#262]
https://github.com/HopkinsIDD/cholera-mapping-pipeline/blame/dev_staninput_refactor/packages/taxdat/R/stan_input_helpers.R#L453

**Comment by eclee25** [comment]
The code is sloppy but the pipeline should work. The _it_ object is in the global environment already when this function is called
https://github.com/HopkinsIDD/cholera-mapping-pipeline/blob/0d1f050f84d5cde5e1f9c5f78091a98a39d3d605/packages/taxdat/R/stan_input_helpers.R#L593
